### PR TITLE
apple-ib-tb: Add more T2 USB HID IDs

### PR DESCRIPTION
**Pull request by aunali1**
Apparently, each variant of the T2 based devices (MacbookPro15,1/2/etc.)
have their own unique associated HID ID. Currently we only support
MacbookPro15,2 (0x027b).

This commit adds support for the following additional devices:
 - MacbookAir8,1 (0x027a)
 - MacbookPro15,1 (0x027c)

Tested working on a MacbookPro15,1 device.

Tested-by: Aun-Ali Zaidi <admin@kodeit.net>
Signed-off-by: Aun-Ali Zaidi <admin@kodeit.net>

### CODE REVIEW

**Comment by roadrunner2** [comment]
Thanks for this pull. However, I think I have a more generic solution, one which doesn't involve constantly adding additional id's every time a new machine/model comes out. I just pushed those changes now - could you see if this latest version works for you? If that approach turns out not to work, then I'll be happy to apply your pull, though.

**Comment by aunali1** [comment]
@roadrunner2 Yep, works fine. I'll go ahead and close this PR.

**Comment by roadrunner2** [comment]
Thanks for testing!

**Comment by aunali1** [comment]
@roadrunner2 Turns out my testing methodology was faulty, The DKMS built module was not being updated properly in my initramfs. After performing a clean rebuild and install I began experiencing the same problem as @mikeeq. My original solution works as expected however.

**Comment by roadrunner2** [comment]
@aunali1 Just found and fixed the issue (stupid mistake!). Please try it again.

**Pull request closed without merging**
